auth:
  token: "bot-token-here"

postgres:
  database: versare
  user: pguser
  password: pgpasswd123
  host: localhost
  port: 5432

intents:
  bans: true
  guilds: true
  guild_messages: true
  members: true

allowed-mentions:
  users: true
  replied_user: true
  roles: false
  everyone: false

defaults:
  prefix: "v."